export const keys = [
  { name: "AC", id: "clear", className: "bg-medium-carmine col-span-2" },
  { name: "/", id: "divide", className: "bg-granite-gray" },
  { name: "*", id: "multiply", className: "bg-granite-gray" },
  { name: "7", id: "seven", className: "bg-dark-liver" },
  { name: "8", id: "eight", className: "bg-dark-liver" },
  { name: "9", id: "nine", className: "bg-dark-liver" },
  { name: "-", id: "subtract", className: "bg-granite-gray" },
  { name: "4", id: "four", className: "bg-dark-liver" },
  { name: "5", id: "five", className: "bg-dark-liver" },
  { name: "6", id: "six", className: "bg-dark-liver" },
  { name: "+", id: "add", className: "bg-granite-gray" },
  { name: "1", id: "one", className: "bg-dark-liver" },
  { name: "2", id: "two", className: "bg-dark-liver" },
  { name: "3", id: "three", className: "bg-dark-liver" },
  { name: "=", id: "equals", className: "bg-regal-blue row-span-2" },
  { name: "0", id: "zero", className: "bg-dark-liver col-span-2" },
  { name: ".", id: "decimal", className: "bg-dark-liver" },
]
